// Tasks / to-dos. Org-scoped, any member can CRUD (RLS). A task can be assigned
// to a user (assignee_user_id) and linked to an entity. public_id (TASK-####) is
// auto-generated by a DB trigger.

import { supabase } from '../supabase';

export type TaskStatus = 'open' | 'done';
export type TaskPriority = 'low' | 'medium' | 'high';

export interface TaskRow {
  id: string;
  public_id: string;
  title: string;
  description: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  type: string;
  due_date: string | null;
  assignee_user_id: string | null;
  linked_entity_type: string | null;
  linked_entity_id: string | null;
  created_by: string;
  created_at: string;
}

const COLS =
  'id, public_id, title, description, status, priority, type, due_date, assignee_user_id, linked_entity_type, linked_entity_id, created_by, created_at';

export async function listTasks(
  orgId: string,
  opts: { assigneeUserId?: string | null; status?: TaskStatus | 'all' } = {},
): Promise<TaskRow[]> {
  let q = supabase
    .from('tasks')
    .select(COLS)
    .eq('org_id', orgId)
    .is('deleted_at', null)
    .order('status', { ascending: true })
    .order('due_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: false });
  if (opts.assigneeUserId) q = q.eq('assignee_user_id', opts.assigneeUserId);
  if (opts.status && opts.status !== 'all') q = q.eq('status', opts.status);
  const { data, error } = await q;
  if (error) throw new Error(error.message);
  return (data ?? []) as TaskRow[];
}

/** Count of open tasks assigned to a user (for the More-menu badge). */
export async function countMyOpenTasks(orgId: string, userId: string): Promise<number> {
  const { count, error } = await supabase
    .from('tasks')
    .select('id', { count: 'exact', head: true })
    .eq('org_id', orgId)
    .eq('assignee_user_id', userId)
    .eq('status', 'open')
    .is('deleted_at', null);
  if (error) return 0;
  return count ?? 0;
}

export async function createTask(input: {
  orgId: string;
  createdBy: string;
  title: string;
  description?: string | null;
  priority?: TaskPriority;
  type?: string;
  dueDate?: string | null;
  assigneeUserId?: string | null;
  linkedEntityType?: TaskRow['linked_entity_type'];
  linkedEntityId?: string | null;
}): Promise<TaskRow> {
  const { data, error } = await supabase
    .from('tasks')
    .insert({
      org_id: input.orgId,
      created_by: input.createdBy,
      title: input.title.trim(),
      description: input.description ?? null,
      priority: input.priority ?? 'medium',
      type: input.type ?? 'Admin',
      due_date: input.dueDate ?? null,
      assignee_user_id: input.assigneeUserId ?? null,
      linked_entity_type: input.linkedEntityType ?? null,
      linked_entity_id: input.linkedEntityId ?? null,
      status: 'open',
    })
    .select(COLS)
    .single();
  if (error) throw new Error(error.message);
  return data as TaskRow;
}

export async function setTaskStatus(id: string, status: TaskStatus): Promise<void> {
  const { error } = await supabase
    .from('tasks')
    .update({ status, completed_at: status === 'done' ? new Date().toISOString() : null })
    .eq('id', id);
  if (error) throw new Error(error.message);
}

export async function deleteTask(id: string): Promise<void> {
  const { error } = await supabase
    .from('tasks')
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', id);
  if (error) throw new Error(error.message);
}
