/**
 * Les mots de la carte de confirmation : libellés des paramètres et valeurs traduites.
 * ─────────────────────────────────────────────────────────────────────────
 * Avant (2026-10-01), 22 paramètres avaient un libellé ; les 168 autres s'affichaient
 * sous leur nom technique, mis en majuscule : « First name », « Send via », « Valid days »,
 * « Also delete lead: Oui », en anglais même dans l'interface française. Les valeurs
 * d'énumération sortaient brutes (« e-transfer », « sales_rep », « link_only »), un taux
 * sans « % », un jour de semaine en chiffre.
 *
 * Un paramètre non identifiant d'un outil d'écriture sans libellé ici fait échouer
 * tests/lumi-libelles-cartes.test.ts.
 */
export const LIBELLES_PARAMETRES: Record<string, [fr: string, en: string]> = {
  action_type: ['Type d’envoi', 'Message type'],
  clear_assignee: ['Retirer le responsable', 'Remove the owner'],
  clock_in_at: ['Arrivée', 'Clock-in'],
  clock_out_at: ['Départ', 'Clock-out'],
  company_name: ['Nom de l’entreprise', 'Company name'],
  discount_type: ['Type de rabais', 'Discount type'],
  discount_value: ['Rabais', 'Discount'],
  expected_close_date: ['Fermeture visée', 'Target close date'],
  granted: ['Consentement accordé', 'Consent granted'],
  paused: ['Tout arrêter', 'Stop everything'],
  pipeline: ['Pipeline', 'Pipeline'],
  revenue_goal_cents: ['Objectif de revenus annuel', 'Annual revenue goal'],
  street1: ['Adresse (rue)', 'Street address'],
  street2: ['Complément d’adresse', 'Address line 2'],
  template_key: ['Modèle d’automatisation', 'Automation template'],
  website: ['Site web', 'Website'],
  address: ['Adresse', 'Address'],
  ai_summaries_enabled: ['Résumés par IA', 'AI summaries'],
  amount_cents: ['Montant', 'Amount'],
  amount_dollars: ['Montant', 'Amount'],
  anchor_date: ['Date de départ du cycle', 'Cycle start date'],
  apres_debut: ['Nouveau début', 'New start'],
  apres_fin: ['Nouvelle fin', 'New end'],
  archived: ['Archivé', 'Archived'],
  assessment_end_at: ['Fin de l’évaluation', 'Assessment end'],
  assessment_instructions: ['Instructions d’évaluation', 'Assessment instructions'],
  assessment_start_at: ['Début de l’évaluation', 'Assessment start'],
  auto_followup_days: ['Relance automatique (jours)', 'Automatic follow-up (days)'],
  auto_revisit_days: ['Revisite automatique (jours)', 'Automatic revisit (days)'],
  auto_send: ['Envoi automatique au client', 'Automatic sending to the client'],
  billing_split: ['Facturation en plusieurs versements', 'Split billing'],
  body: ['Message', 'Message'],
  category: ['Catégorie', 'Category'],
  changements: ['Changements', 'Changes'],
  channel: ['Canal', 'Channel'],
  city: ['Ville', 'City'],
  clear_team: ['Retirer l’équipe', 'Remove the team'],
  client_name: ['Client', 'Client'],
  client_note: ['Note au client', 'Note to the client'],
  color: ['Couleur', 'Colour'],
  color_hex: ['Couleur', 'Colour'],
  company: ['Entreprise', 'Company'],
  completed: ['Terminé', 'Completed'],
  content_type: ['Type de contenu', 'Content type'],
  cost_cents: ['Coût', 'Cost'],
  country: ['Pays', 'Country'],
  custom_email_body: ['Texte du courriel', 'Email text'],
  custom_email_subject: ['Objet du courriel', 'Email subject'],
  custom_sms_body: ['Texte du texto', 'Text message'],
  customer_email: ['Courriel du client', 'Client email'],
  customer_name: ['Nom du client', 'Client name'],
  customer_phone: ['Téléphone du client', 'Client phone'],
  d2d_status: ['Statut terrain', 'Field status'],
  date: ['Date', 'Date'],
  day_of_month: ['Jour du mois', 'Day of the month'],
  day_of_week: ['Jour de la semaine', 'Day of the week'],
  days_after_due: ['Jours après l’échéance', 'Days after the due date'],
  deposit_required: ['Dépôt exigé', 'Deposit required'],
  deposit_type: ['Type de dépôt', 'Deposit type'],
  deposit_value: ['Dépôt', 'Deposit'],
  description: ['Description', 'Description'],
  description_en: ['Description (anglais)', 'Description (English)'],
  description_fr: ['Description (français)', 'Description (French)'],
  display_name: ['Nom affiché', 'Display name'],
  due_date: ['Échéance', 'Due date'],
  due_days_offset: ['Délai de paiement (jours)', 'Payment delay (days)'],
  duration_min: ['Durée (minutes)', 'Duration (minutes)'],
  duration_minutes: ['Durée (minutes)', 'Duration (minutes)'],
  email: ['Courriel', 'Email'],
  email_body: ['Texte du courriel', 'Email text'],
  email_subject: ['Objet du courriel', 'Email subject'],
  embed_url: ['Lien intégré', 'Embed link'],
  empreinte: ['Référence de la proposition', 'Proposal reference'],
  enabled: ['Activé', 'Enabled'],
  end_at: ['Fin', 'End'],
  end_date: ['Date de fin', 'End date'],
  end_time: ['Heure de fin', 'End time'],
  entity_type: ['Type de fiche', 'Record type'],
  estimated_value: ['Valeur estimée', 'Estimated value'],
  event_type: ['Résultat', 'Outcome'],
  feature_enabled: ['Module activé', 'Module enabled'],
  first_name: ['Prénom', 'First name'],
  footer_notes: ['Notes de bas de page', 'Footer notes'],
  frequency: ['Fréquence', 'Frequency'],
  from: ['Du', 'From'],
  hourly_rate_cents: ['Taux horaire', 'Hourly rate'],
  icon: ['Icône', 'Icon'],
  instruction: ['Modification demandée', 'Requested change'],
  must_be_shorter: ['Plus court que l’actuel', 'Shorter than the current one'],
  internal_notes: ['Notes internes', 'Internal notes'],
  interval_days: ['Intervalle (jours)', 'Interval (days)'],
  intro_text: ['Texte d’introduction', 'Intro text'],
  is_active: ['Active', 'Active'],
  is_compound: ['Taxe composée', 'Compound tax'],
  is_default: ['Par défaut', 'Default'],
  is_exclusive: ['Exclusif', 'Exclusive'],
  is_optional: ['Optionnel', 'Optional'],
  is_primary: ['Adresse principale', 'Primary address'],
  item_type: ['Type d’article', 'Item type'],
  items: ['Articles', 'Items'],
  job_title: ['Titre du job', 'Job title'],
  job_type: ['Type de job', 'Job type'],
  key: ['Clé', 'Key'],
  kind: ['Genre', 'Kind'],
  label: ['Libellé', 'Label'],
  language: ['Langue', 'Language'],
  last_name: ['Nom de famille', 'Last name'],
  lat: ['Latitude', 'Latitude'],
  latitude: ['Latitude', 'Latitude'],
  layout_type: ['Mise en page', 'Layout'],
  line_items: ['Lignes', 'Line items'],
  lng: ['Longitude', 'Longitude'],
  longitude: ['Longitude', 'Longitude'],
  lost_reason: ['Raison de la perte', 'Loss reason'],
  make_default: ['Mettre par défaut', 'Make default'],
  max_occurrences: ['Nombre maximal de répétitions', 'Maximum occurrences'],
  message: ['Message', 'Message'],
  message_number: ['Numéro du message', 'Message number'],
  message_text: ['Message', 'Message'],
  method: ['Mode de paiement', 'Payment method'],
  metric: ['Mesure', 'Metric'],
  metric_slug: ['Mesure', 'Metric'],
  milestones: ['Jalons', 'Milestones'],
  name: ['Nom', 'Name'],
  name_en: ['Nom (anglais)', 'Name (English)'],
  name_fr: ['Nom (français)', 'Name (French)'],
  next_run_date: ['Prochaine date', 'Next date'],
  no_taxes: ['Sans taxes', 'No taxes'],
  note: ['Note', 'Note'],
  note_text: ['Note', 'Note'],
  notes: ['Notes', 'Notes'],
  pay_day_offset: ['Délai avant la paie (jours)', 'Days before payday'],
  pay_period_type: ['Cycle de paie', 'Pay cycle'],
  payment_terms: ['Conditions de paiement', 'Payment terms'],
  percent: ['Pourcentage', 'Percentage'],
  period: ['Période', 'Period'],
  period_end: ['Fin de la période', 'Period end'],
  period_ref: ['Période', 'Period'],
  period_start: ['Début de la période', 'Period start'],
  permissions: ['Permissions', 'Permissions'],
  phone: ['Téléphone', 'Phone'],
  phone_number: ['Téléphone', 'Phone'],
  polygon: ['Zone', 'Area'],
  postal_code: ['Code postal', 'Postal code'],
  preset_key: ['Région fiscale', 'Tax region'],
  price_cents: ['Prix', 'Price'],
  pricing_unit: ['Unité de prix', 'Pricing unit'],
  priority: ['Priorité', 'Priority'],
  prize_description: ['Prix à gagner', 'Prize'],
  property_address: ['Adresse de service', 'Service address'],
  province: ['Province', 'Province'],
  publish: ['Publier', 'Publish'],
  qty: ['Quantité', 'Quantity'],
  quantity: ['Quantité', 'Quantity'],
  quote_title: ['Titre du devis', 'Quote title'],
  rate: ['Taux', 'Rate'],
  reason: ['Raison', 'Reason'],
  recipient_email: ['Destinataire', 'Recipient'],
  region: ['Région', 'Region'],
  registration_number: ['Numéro d’enregistrement', 'Registration number'],
  reminders: ['Relances', 'Reminders'],
  require_signature: ['Signature exigée', 'Signature required'],
  required: ['Obligatoire', 'Required'],
  responses: ['Réponses', 'Answers'],
  restore: ['Désarchiver', 'Unarchive'],
  role: ['Rôle', 'Role'],
  schedule: ['Calendrier des relances', 'Reminder schedule'],
  scheduled_at: ['Planifié le', 'Scheduled for'],
  scope: ['Portée', 'Scope'],
  send_via: ['Envoyer par', 'Send by'],
  services: ['Services', 'Services'],
  slug: ['Nom court', 'Short name'],
  sort_order: ['Ordre', 'Order'],
  source: ['Source', 'Source'],
  stage: ['Étape', 'Stage'],
  start_at: ['Début', 'Start'],
  start_date: ['Date de début', 'Start date'],
  start_time: ['Heure de début', 'Start time'],
  status: ['Statut', 'Status'],
  subject: ['Objet', 'Subject'],
  tag: ['Étiquette', 'Tag'],
  tags: ['Étiquettes', 'Tags'],
  target_roles: ['Rôles visés', 'Target roles'],
  target_value: ['Cible', 'Target'],
  tax_cents: ['Taxes', 'Taxes'],
  tax_enabled: ['Taxes appliquées', 'Taxes applied'],
  tax_label: ['Nom de la taxe', 'Tax name'],
  tax_rate: ['Taux de taxe', 'Tax rate'],
  taxable: ['Taxable', 'Taxable'],
  taxes: ['Taxes', 'Taxes'],
  terms: ['Conditions', 'Terms'],
  territory_restriction_enabled: ['Restriction par territoire', 'Territory restriction'],
  text: ['Texte', 'Text'],
  text_content: ['Texte', 'Text'],
  timezone: ['Fuseau horaire', 'Time zone'],
  title: ['Titre', 'Title'],
  to: ['Au', 'To'],
  type: ['Type', 'Type'],
  unit_price_cents: ['Prix unitaire', 'Unit price'],
  valid_days: ['Validité (jours)', 'Valid for (days)'],
  value: ['Valeur', 'Value'],
  variables: ['Variables', 'Variables'],
  video_url: ['Lien de la vidéo', 'Video link'],
  visibility: ['Visibilité', 'Visibility'],
  voice_notes_enabled: ['Notes vocales', 'Voice notes'],
  weekday: ['Jour de la semaine', 'Day of the week'],
};

/** Paramètres dont la valeur est un choix dans une liste : la valeur se traduit. */
export const PARAMETRES_A_CHOIX = new Set([
  'status', 'stage', 'role', 'method', 'reason', 'send_via', 'channel', 'frequency', 'period', 'pay_period_type', 'priority',
  'action_type', 'type', 'scope', 'language', 'item_type', 'kind', 'deposit_type', 'pricing_unit', 'metric', 'metric_slug',
  'event_type', 'd2d_status', 'visibility', 'content_type', 'entity_type', 'layout_type', 'discount_type',
]);

export const VALEURS_TRADUITES: Record<string, [fr: string, en: string]> = {
  // Modes de paiement
  cash: ['Comptant', 'Cash'], 'e-transfer': ['Virement Interac', 'E-transfer'], check: ['Chèque', 'Cheque'], cheque: ['Chèque', 'Cheque'], card: ['Carte', 'Card'],
  // Fréquences et périodes
  daily: ['Chaque jour', 'Daily'], weekly: ['Chaque semaine', 'Weekly'], biweekly: ['Aux deux semaines', 'Every two weeks'],
  semimonthly: ['Deux fois par mois', 'Twice a month'], monthly: ['Chaque mois', 'Monthly'], quarterly: ['Chaque trimestre', 'Quarterly'],
  yearly: ['Chaque année', 'Yearly'], custom: ['Personnalisée', 'Custom'],
  // Canaux
  email: ['Courriel', 'Email'], sms: ['Texto', 'Text message'], both: ['Courriel et texto', 'Email and text message'],
  link_only: ['Lien seulement, rien n’est envoyé', 'Link only, nothing is sent'],
  send_sms: ['Texto', 'Text message'], send_email: ['Courriel', 'Email'],
  // Raisons
  requested_by_customer: ['Demandé par le client', 'Requested by the client'], duplicate: ['Paiement en double', 'Duplicate payment'],
  fraudulent: ['Paiement frauduleux', 'Fraudulent payment'], declined: ['Refusée par le client', 'Declined by the client'], archived: ['Archivée', 'Archived'],
  // Rôles et portées
  owner: ['Propriétaire', 'Owner'], admin: ['Administrateur', 'Admin'], manager: ['Gestionnaire', 'Manager'], sales_rep: ['Représentant', 'Sales rep'],
  technician: ['Technicien', 'Technician'], team_leader: ['Chef d’équipe', 'Team leader'],
  self: ['Ses propres fiches', 'Own records'], assigned: ['Ce qui lui est assigné', 'What is assigned to them'], team: ['Son équipe', 'Their team'], company: ['Toute l’entreprise', 'Whole company'],
  // Statuts
  done: ['Terminée', 'Done'], open: ['À faire', 'Open'], draft: ['Brouillon', 'Draft'], published: ['Publiée', 'Published'],
  scheduled: ['Planifié', 'Scheduled'], in_progress: ['En cours', 'In progress'], completed: ['Terminé', 'Completed'], cancelled: ['Annulé', 'Cancelled'],
  unknown: ['Inconnu', 'Unknown'], no_answer: ['Pas de réponse', 'No answer'], not_interested: ['Pas intéressé', 'Not interested'], lead: ['Prospect', 'Lead'],
  quote_sent: ['Devis envoyé', 'Quote sent'], sale: ['Vente', 'Sale'], callback: ['À rappeler', 'Call back'], do_not_knock: ['Ne pas cogner', 'Do not knock'],
  revisit: ['À revisiter', 'Revisit'], pending: ['En attente', 'Pending'], follow_up: ['Suivi', 'Follow-up'], hot: ['Chaud', 'Hot'], cold: ['Froid', 'Cold'],
  // Étapes de l'ancien pipeline
  new_prospect: ['Nouveau prospect', 'New lead'], no_response: ['Pas de réponse', 'No response'], closed_won: ['Gagné', 'Won'], closed_lost: ['Perdu', 'Lost'],
  // Divers
  fr: ['Français', 'French'], en: ['Anglais', 'English'],
  service: ['Service', 'Service'], product: ['Produit', 'Product'], billing: ['Facturation', 'Billing'],
  percentage: ['Pourcentage', 'Percentage'], fixed: ['Montant fixe', 'Fixed amount'],
  flat: ['Prix fixe', 'Flat price'], linear_ft: ['Au pied linéaire', 'Per linear foot'], sq_ft: ['Au pied carré', 'Per square foot'],
  revenue: ['Revenus', 'Revenue'], jobs: ['Jobs', 'Jobs'], leads: ['Prospects', 'Leads'], knocks: ['Portes cognées', 'Doors knocked'], sales: ['Ventes', 'Sales'],
  quotes_sent: ['Devis envoyés', 'Quotes sent'], callbacks: ['Rappels', 'Callbacks'], knock: ['Porte cognée', 'Door knocked'], cancel: ['Annulation', 'Cancellation'],
  all: ['Tout le monde', 'Everyone'], video: ['Vidéo', 'Video'], embed: ['Contenu intégré', 'Embedded content'], text: ['Texte', 'Text'], pdf: ['PDF', 'PDF'], link: ['Lien', 'Link'],
  classic: ['Classique', 'Classic'], modern: ['Moderne', 'Modern'], minimal: ['Minimaliste', 'Minimal'], bold: ['Affirmée', 'Bold'], executive: ['Exécutive', 'Executive'], contractor: ['Entrepreneur', 'Contractor'],
  approved: ['Approuvé', 'Approved'], awaiting_response: ['En attente de réponse', 'Awaiting response'],
  high: ['Haute', 'High'], medium: ['Moyenne', 'Medium'], low: ['Basse', 'Low'], urgent: ['Urgente', 'Urgent'],
  client: ['Client', 'Client'], job: ['Job', 'Job'], quote: ['Devis', 'Quote'], invoice: ['Facture', 'Invoice'], deal: ['Deal', 'Deal'],
  note: ['Note', 'Note'], checkbox: ['Case à cocher', 'Checkbox'], number: ['Nombre', 'Number'], photo: ['Photo', 'Photo'], signature: ['Signature', 'Signature'],
  invoice_sent: ['Facture envoyée', 'Invoice sent'], invoice_reminder: ['Relance de facture', 'Invoice reminder'], quote_accepted: ['Devis approuvé', 'Quote accepted'],
  quote_declined: ['Devis refusé', 'Quote declined'], job_confirmation: ['Confirmation de job', 'Job confirmation'], job_reminder: ['Rappel de job', 'Job reminder'],
  job_completed: ['Job terminé', 'Job completed'], review_request: ['Demande d’avis', 'Review request'], generic: ['Général', 'General'],
};

/** Paramètres dont le nombre est un pourcentage. */
export const PARAMETRES_EN_POURCENT = new Set(['rate', 'tax_rate', 'percent']);
/** Paramètres dont le nombre est un jour de semaine (0 = dimanche … 6 = samedi). */
export const PARAMETRES_JOUR_SEMAINE = new Set(['weekday', 'day_of_week']);
export const JOURS_SEMAINE: Array<[fr: string, en: string]> = [
  ['dimanche', 'Sunday'], ['lundi', 'Monday'], ['mardi', 'Tuesday'], ['mercredi', 'Wednesday'], ['jeudi', 'Thursday'], ['vendredi', 'Friday'], ['samedi', 'Saturday'],
];
