/**
 * Carte de l'app pour l'assistant de support : routes et libellés EXACTS,
 * relevés dans le code (src/App.tsx, src/i18n/fr.ts, pages) le 2026-09-15,
 * relus le 2026-09-17 (Lume Payments refait #415/#418/#421/#425, Commissions #419/#420, Feuilles de temps « Ma paie » #423).
 * Fraîcheur gardée par tests/support/carte-app-fraicheur.test.ts : une page
 * dont les libellés changent fait échouer le test tant que la carte n'a pas
 * été relue (puis `npm run carte:empreinte`).
 * C'est ce qui permet à Lumi de répondre à un « comment faire » sans
 * transférer à l'équipe. Règle : rien ici qui n'existe pas dans l'interface.
 * Couverture garantie par tests/support/carte-app-complete.test.ts : chaque
 * route de App.tsx et chaque page des Paramètres doit y être nommée.
 * Depuis le 2026-09-17, la carte complète n'entre PLUS dans le prompt du
 * support : elle est indexée par search_help (server/lib/agent/tools-aide.ts)
 * et le modèle ne reçoit que son INDEX (indexCarteApp : les écrans et leurs
 * routes, ~1 000 tokens au lieu de ~7 000). La grossir ne coûte donc rien
 * par tour ; seul l'index est en cache 1 h.
 */
/**
 * L'index de la carte : la ligne de vocabulaire, puis par section les écrans
 * avec leur route (« Tâches (/tasks) · Jobs (/jobs) · … »). Assez pour que
 * le modèle sache QUELS écrans existent et où ; les boutons exacts viennent
 * de search_help. Pur, dérivé de CARTE_APP : impossible de désynchroniser.
 */
export function indexCarteApp(carte: string = CARTE_APP): string {
  const lignes = carte.split('\n');
  const out: string[] = [lignes[0].trim()];
  let section = '';
  let ecrans: string[] = [];
  const vider = () => { if (section && ecrans.length) out.push(`${section} : ${ecrans.join(' · ')}`); ecrans = []; };
  for (const brute of lignes.slice(1)) {
    const ligne = brute.trim();
    if (!ligne) continue;
    const titreSection = /^═+\s*(.+?)\s*═+$/.exec(ligne);
    if (titreSection) { vider(); section = titreSection[1].replace(/\s*\(.*\)\s*$/, ''); continue; }
    const m = /^([^:(]+?)\s*(\(([^)]*)\))?\s*:\s*/.exec(ligne);
    if (!m) continue;
    const route = /\/[a-z0-9\-/:]+/i.exec(m[3] ?? '')?.[0];
    ecrans.push(route ? `${m[1].trim()} (${route})` : m[1].trim());
  }
  vider();
  return out.join('\n');
}

export const CARTE_APP = `Vocabulaire : « tâches » = à-faire de la page Tâches (/tasks) ; « travaux » / « jobs » = travail planifié (/jobs) ; « devis » = soumission (/quotes) ; « facture » (/finances, onglet Facturation). Paramètres = menu « Paramètres » (/settings), groupé en Mon compte, Entreprise, Ventes & paiements, Communication, Équipe, Plus.

═══ TRAVAIL QUOTIDIEN ═══
Accueil (/day ; /dashboard et /lume-agent y renvoient) : vue de la journée en lecture (météo, indicateurs, agenda du jour, revenus, tâches, pipeline, comptes à recevoir) ; chaque carte mène à sa section.
Tâches (/tasks) : sur la ligne de la tâche, icône corbeille « Supprimer » ou menu « … » → « Supprimer » ; plusieurs tâches : cases à cocher → « Supprimer ». Aucune confirmation, suppression immédiate (toast « Tâche supprimée »), pas de restauration.
Jobs (/jobs) : ligne → menu « … » → « Supprimer » → confirmation « Supprimer cette job ? » (masquée des vues actives, bouton « Annuler » dans le toast quelques secondes). En lot : cases à cocher → « Supprimer ». Il n'y a PAS de bouton « Archiver » ni « Annuler la job » : l'onglet « Archivé » montre les jobs complétées ou annulées. Sur /jobs/:id, « Plus d'actions » offre : Fermer le job, Envoyer une confirmation / un suivi / un courriel, Créer une facture, Dupliquer le job, Télécharger le PDF, Imprimer.
Replanifier une job : dans le Calendrier (/calendar), glisser l'événement (ou l'étirer) ; ou /jobs/:id → carte de la visite → « Plus d'actions » → « Modifier la visite » (date, heure, équipe) → « Enregistrer » ; « Retirer la visite » au même endroit.
Calendrier (/calendar) : vues jour / semaine / mois, bouton « + Créer » (Job ou Tâche), glisser-déposer des jobs non planifiées depuis le tiroir.
Carte de répartition (/dispatch) : techniciens et jobs en temps réel ; « Jobs (n) », « Géofences », « Synchroniser », « Retour ».
Clients (/clients, fiche /clients/:id) : archiver = fiche → « … » → « Archiver » (confirmation : ses jobs, factures et devis restent visibles) ; restaurer ou supprimer définitivement dans Paramètres → Archives (/settings/archives). Supprimer définitivement = /clients/:id/edit → bouton rouge « Supprimer » (efface tous les enregistrements liés). Notes : bloc « Notes » en bas de la fiche, enregistré au clic hors du champ ou « Enregistrer » ; onglet « Notes spécifiques » à part. « Exporter les données » et « Supprimer les données (Loi 25) » dans le menu « … » de la fiche. Import CSV de clients : /clients → « Importer ». Il n'y a pas d'export CSV de la liste des clients. Nouveau client : /clients/new.
Demandes (/requests) : boîte des demandes reçues par le formulaire public ; « Archivées (n) », « Actualiser » ; liste vide → « Copier » / « Ouvrir » le lien du formulaire, « Modifier le formulaire ». Fiche (/requests/:id) : « Planifier une évaluation » ; menu « Plus » → « Convertir en devis », « Convertir en job », « Archiver » / « Désarchiver », « Imprimer », « Supprimer » (confirmation « Supprimer cette demande ? »). /leads renvoie vers /quotes.
Devis (/quotes, nouveau /quotes/new) : ligne → « … » → « Archiver » / « Désarchiver » (sans confirmation) ou « Supprimer » (confirmation). Sur /quotes/:id : « Convertir en facture », « Supprimer », ou marquer la soumission comme refusée. Il n'y a pas de bouton « Annuler le devis ». Dépôt : un devis avec dépôt exigé est payé en ligne par le client au moment d'accepter (si « Paiement des devis » est activé dans Lume Payments) ; « Carte au dossier exigée » se règle par devis, sa valeur par défaut dans Lume Payments. Modèles de devis (/quotes/presets, alias /quotes/templates) : « Nouveau modèle », « Modifier », « Dupliquer le modèle », « Supprimer le modèle » (confirmation « Supprimer "…" ? ») ; éditeur : « Ajouter une section », « Aperçu », « Sauvegarder ». Mesure sur carte (/quotes/measure, /quotes/:id/measure) : « Rechercher une adresse », tracer, « Terminer », « Capture d'écran », « Sauvegarder », « Envoyer au devis » (confirmation), « Supprimer la mesure ».
Messages (/messages) : textos bidirectionnels ; « Nouveau message » (chercher un client ou saisir un numéro, puis « Envoyer ») ; « Rechercher… » ; « Tapez un message… » puis « Envoyer ». Le numéro dédié se configure dans Paramètres → Messagerie SMS (/settings/messaging) : « Obtenir mon numéro », « Actualiser », « Copier », « Tester votre numéro » → « Envoyer le test ».
Recherche (/search) : résultats de la recherche globale ; « Ouvrir l'onglet … » filtre par type ; « Précédent » / « Suivant ».
Lumi, l'assistant dans l'app (/lumi) : agit dans les données du CRM (devis, jobs, factures…), différent du support ; « Pose-moi une question… » puis « Envoyer », « Parler à Lumi » (dictée), « Nouvelle conversation », « Historique », réglage « Ce que Lumi fait sans te demander » ; « Supprimer la conversation » (confirmation).

═══ ARGENT ═══
Finances (/finances ; /invoices et /payments y renvoient) : trois onglets « Facturation », « Paiements », « Versements ».
- Facturation : « Nouvelle facture » (/invoices/new : choisir le client, « Ajouter » une ligne, « Aperçu », « Sauvegarder », « Envoyer » ; /invoices/:id/edit pour modifier), « CSV » (export), menu « … » par facture → « Voir », « Envoyer », « Marquer payée », « Dupliquer », « Supprimer » (confirmation « Supprimer cette facture ? » ; en lot « Supprimer N facture(s) ? »). Sur la fiche /invoices/:id : menu « … » → « Marquer payée » (confirmation) ou « Annuler » (annule la facture, confirmation), « Dupliquer ».
- Paiements : liste des paiements reçus (carte, comptant, chèque) ; filtres « Statut » / « Méthode » / « Période » ; « Paramètres » → Lume Payments ; « Activer » si Lume Payments n'est pas branché.
- Versements : argent déposé au compte bancaire (Stripe) ; tuiles « Disponible » / « En route » / « Déposé » ; une ligne ouvre « Détails du versement » ; « Ouvrir les paramètres » si non connecté.
Lume Payments (Paramètres → Lume Payments, /settings/payments ; /payments/settings et /settings/reminders y renvoient) : connexion Stripe pour encaisser en ligne (aucun frais mensuel, frais par transaction, carte « Taux de traitement »). Les réglages sont visibles avant l'activation Stripe. Carte « Paiements du portail client » : interrupteurs « Paiement des devis » (le client paie son dépôt en ligne en acceptant le devis), « Paiement des factures » (lien de paiement), et sous chacun la ligne « Paiements par carte » avec les logos Visa, Mastercard, American Express, Apple Pay et Google Pay (les deux derniers disparaissent si l'interrupteur « Apple Pay & Google Pay » est fermé). Carte « Réglages avancés » : « Apple Pay & Google Pay » (proposés sur la page de paiement en plus de la carte), « Carte au dossier » (exiger une carte enregistrée quand le client accepte un devis ; ajustable par devis), « Pourboires » (accepter un pourboire sur les factures payées en ligne, jamais déduit du solde). Carte « Notifications » : « Être avisé de chaque paiement par courriel » (envoyé à l'adresse de l'entreprise), « Reçu automatique au client » (c'est la règle « facture payée » des Automatisations, /automations). « Désactiver les paiements » (confirmation « Désactiver les paiements en ligne ? ») coupe devis et factures d'un coup, réactivable. Carte « Versements » : « Prochain versement », compte de dépôt (« Aucun compte de dépôt » tant qu'il n'est pas ajouté, « Gérer le compte de dépôt »). Carte « Versements instantanés » : « Verser » ; sinon « Configurer » (ajouter une carte de débit dans le tableau de bord Stripe, frais Stripe). Carte « Litiges » : « Réponse requise » / « 0 litige », « Voir » ouvre Stripe. Carte « Rappels de paiement » : interrupteur, « Ajouter un rappel », « Après » N jours, « Canal du rappel » (Courriel ou Courriel + SMS ; « SMS non configuré » sinon), « Retirer ce rappel », « Enregistrer » — relances automatiques des factures en retard, avec le lien de paiement. Carte « Sécurité » : « Vérification par SMS » (« Configurer » / « Changer »), requise pour les actions de paiement sur un nouvel appareil. Les logos « Moyens de paiement acceptés » (Visa, Mastercard, American Express, Apple Pay, Google Pay) figurent aussi sous « Taux de traitement » et sur la page publique /pay/:token, sous le bouton « Payer ». Réservé aux propriétaires et administrateurs. Rien à supprimer.
Taxes (Paramètres → Taxes, /settings/taxes) : « Ajouter une région », « Définir par défaut », « Ajouter une taxe personnalisée », « Ajouter un numéro d'enregistrement », interrupteur par taxe ; suppressions avec confirmation (« Supprimer la région … et toutes ses taxes ? », « Supprimer la taxe … ? »).
Forfait & facturation (Paramètres → Forfait & facturation, /settings/billing ; /pricing y renvoie) : « Carte & factures » (portail Stripe), « Voir tous les plans », « Changer ou rétrograder mon plan », « Passer à … » / « Rétrograder vers … » / « Choisir ce plan » ; une rétrogradation demande confirmation (« Changement de plan », ce qui sera perdu, « Garder mon plan … »). Un changement programmé se retire avec « Annuler ».
Commissions (/commissions) : onglets « Vue d'ensemble », « Représentants », « Mes commissions », « Taux ». Onglet « Taux » : « Plan de commission par membre » (tableau : Membre, Rôle, « Mode de paie » — « À l'heure », « Commission » ou « Horaire + commission », réglé dans la fiche Équipe : « Modifier dans la fiche Équipe » → /settings/team/:memberId —, « Taux horaire », « Plan appliqué », « Taux effectif ») et « Plan par défaut de l'entreprise ». Un membre payé à l'heure ne touche jamais de commission (« Aucun plan : aucune commission ne sera calculée »). Un représentant voit « Mes commissions » (vue en lecture seule, identique à ce que voit le gestionnaire).
Paie (Paramètres → Paie, /settings/payroll) : totaux d'heures par période, « Période précédente » / « Période suivante », ajustements (montant négatif = retenue), marquer un employé payé ou annuler, « Exporter (QuickBooks CSV) ». Sans confirmation.

═══ ÉQUIPE & TEMPS ═══
Membres (Paramètres → Membres, /settings/team ; /manage-team, /settings/users, /d2d-settings/general et /d2d-settings/teams y renvoient) : « Inviter un membre » (courriel + rôle, « Assigner au bureau », « Portée d'accès », « Équipe à assigner (optionnel) », « Envoyer l'invitation »), « Gérer le forfait », menu « … » par membre → « Retirer de l'équipe », « Réactiver l'accès », « Supprimer définitivement » (confirmation « Supprimer définitivement ? ») ; changer un rôle plus tard : « Changer le rôle » (admin, représentant, technicien). Fiche d'un membre : /settings/team/:memberId.
Rôles & Permissions (Paramètres → Rôles, /settings/roles) : choisir un rôle à gauche, cocher les permissions par groupe (enregistré automatiquement, « Enregistré »), « Réinitialiser » aux valeurs par défaut (sans confirmation).
Feuilles de temps (/timesheets ; /availability renvoie vers l'onglet horaire) : onglets « Feuilles de temps » / « Carte » / « Horaire » ; « Exporter » (CSV), « Approuver » (sélection), « Forcer punch-out », « Aujourd'hui » et flèches de période, « Modifier les heures » → « Sauvegarder ». Sans confirmation. Un technicien ou un représentant (sans accès à Paramètres → Paie) y voit aussi la carte « Période de paie actuelle » (sa paie : « Payé à l'heure », « Payé à commission » ou « Horaire + commission » selon sa fiche Équipe ; « Heures travaillées », « Salaire horaire », « Ventes », « Commission à venir », « Total prévu sur la prochaine paie » ; « Taux horaire à 0 $ — à régler dans la fiche Équipe. » si rien n'est réglé).
Localisation GPS (Paramètres → Localisation GPS, /settings/location) : consentement GPS personnel ; pour un propriétaire/admin, interrupteur maître de l'organisation et consentements de l'équipe (Loi 25). Plus d'intégration de traceurs externes.
Formations (/courses ; /training y renvoie) : « Créer une formation », filtres « Publié » / « Brouillon », menu « … » → « Modifier la formation », « Voir », « Dupliquer la formation », « Supprimer la formation » (confirmation : modules, leçons et progressions perdus). Éditeur (/courses/new, /courses/:id/edit) : « Ajouter un module », leçons (« Dupliquer » / « Supprimer » sans confirmation), bascule « Publié » / « Brouillon », « Aperçu », « Enregistrer ». Suivre une formation (/courses/:id) : « Marquer comme terminée », « Leçon suivante », « Votre progression », « Progression de l'équipe ».

═══ VENTE TERRAIN (menu « Vente », visible si le forfait inclut le module, sinon entrée cadenassée) ═══
Map (/field-sales ; /d2d-dashboard y renvoie) : carte de porte-à-porte ; « Ajouter un pin », « Filtrer les pins », « Rechercher une adresse (⌘K) », « Créer une zone », « Sélectionner des pins » → « Supprimer tout » / « Désélectionner », « Passer en vue satellite », « Centrer sur ma position » ; sur un pin : « Appeler », « Envoyer un message », « Envoyer un courriel », « Modifier », « Supprimer le pin » (confirmation « Supprimer ce pin ? », option de supprimer aussi le client lié) ; un pin « lead » propose « Créer un contrat », « Créer un devis », « Passer pour le moment ».
Pipeline (/pipeline ; /d2d-pipeline y renvoie) : kanban des deals ; glisser une carte pour changer d'étape ; « Filtrer » → « Tous les reps » ; panneau de détail « Réassigner à » / « Choisir un rep… », « Fermer ».
Classement (/leaderboard) : « Mon bureau » / « Tous les bureaux », période « Changer » → « Du » / « Au » → « Appliquer », « Tous » / « 1re année » / « Expérimentés », choix du « Bureau », « Rechercher un rep… ». Lecture seule.
Rapports terrain (/d2d-reports) : quotidien / hebdomadaire / mensuel, « Filtres », « Exporter », « Revenu par rep », « Entonnoir de conversion ». Lecture seule.
Profil d'un représentant (/reps/:id) : « Appeler », « Ajouter un courriel », « Ajouter un numéro », indicateurs terrain. Profil terrain à compléter (/d2d-onboarding) : 3 étapes, « Continuer » puis « Terminer ».
Statistiques (/insights) : analyses et rapports ; période (« 12 derniers mois », « 2 dernières années », « 3 dernières années », « 12 dernières semaines », « Cette année à ce jour ») ; les cartes mènent à Finances, Classement, Clients. Lecture seule.

═══ RÉGLAGES ═══
Mon profil (Paramètres → Mon profil, /settings/profile ; /settings/language y renvoie) : « Changer la photo », « Changer la bannière », courriel → « Changer » → « Envoyer le lien de confirmation », section « Langue de l'interface » (« Français » / « English », appliqué tout de suite — ne pas dire « Paramètres → Langue »), « Enregistrer », « Mes statistiques ». La langue des messages envoyés AUX CLIENTS se choisit dans /automations (« Messages en » FR / EN).
Paramètres entreprise (Paramètres → Paramètres entreprise, /settings/company ; /company-settings y renvoie) : logo (téléversé et enregistré tout de suite, « Supprimer » le logo sans confirmation), couleur de marque (« Revenir au noir »), téléphone, site web, courriel, adresse → « Enregistrer » (« Modifications non sauvegardées » / « Tout est à jour »). Carte « Envoyer depuis mon adresse » : par défaut les factures, devis et contrats partent de noreply@lumecrm.net au nom de l'entreprise ; en saisissant son domaine (« Domaine » → « Activer »), l'entreprise obtient des enregistrements DNS à copier chez son hébergeur (Type / Nom / Valeur, bouton « Copier » par ligne), puis « Vérifier » ; une fois « Vérifié », les courriels partent de facturation@sondomaine.ca et « Retirer » revient à l'adresse Lume.
Bureaux (Paramètres → Bureaux, /settings/offices) : « Nouveau bureau » (/offices/new : « Nom du bureau » obligatoire, coordonnées facultatives, options de copie logo/taxes/modèles/étiquettes, « Créer le bureau »), « Ajouter un bureau au forfait » si la limite est atteinte, « Ouvrir » un bureau ; étiquettes « Principal », « Actuel », « Pas membre ».
Produits & Services (Paramètres → Produits & Services, /settings/products) : « Nouveau service » → « Créer le service » / « Enregistrer » ; crayon « Modifier » ; corbeille « Supprimer » (confirmation « Supprimer « nom » ? »).
Automatisations (/automations ; /automations/builder et /automations/hub y renvoient) : interrupteur à droite de chaque règle (« Activer » / « Désactiver »), sans confirmation ; filtres « Catégorie » et « Statut » (« Toutes » / « Actives » / « Inactives ») ; « Messages en » FR / EN ; panneau « Description », « Actions », « Détails ». Rien à supprimer.
Avis clients (Paramètres → Avis clients, /settings/reviews) : interrupteur « Demander un avis à la fin de chaque job », « Fiche Google (Google Business Profile) », « Page Facebook (onglet Avis) », « Enregistrer », « Aperçu client », « Automatisations liées ».
Formulaire de demande (Paramètres → Formulaire de demande, /settings/request-form) : « Ajouter un champ », « Ajouter une option », « Aperçu », « Enregistrer », code d'intégration « Copier ce code et le coller dans votre site web ».
Archives (Paramètres → Archives, /settings/archives) : clients, devis et jobs archivés ; filtres « Tous » / « Clients » / « Devis » / « Jobs » ; « Restaurer » (confirmation) et « Supprimer définitivement » (confirmation, irréversible). Les tâches supprimées n'y sont pas.
Marketplace / Connexions (Paramètres → Marketplace, /settings/marketplace ; /marketplace y renvoie) : par application « Connecter » / « Activer » / « Gérer », « Tester la connexion », « Renouveler », « Reconnecter », « Déconnecter » (confirmation « Confirmer » / « Annuler »).
API & MCP (Paramètres → API & MCP, /settings/api) : brancher le CRM à Claude ; « Adresse du serveur MCP » (« Copier »), « Trois étapes, une minute ».
Support (Paramètres → Support, /settings/support) : « Rechercher dans l'aide… », « Questions fréquentes », « Aller à la page → », « Nous écrire ». Le bouton « Aide » (bouée, en bas à droite) ouvre le même Lumi.
Vie privée et données (/account/privacy) : « Télécharger » (export de ses données), demande de suppression du compte (« Motif (optionnel) » → « Envoyer la demande », réponse sous 30 jours), « Réinitialiser les préférences de témoins ».
Sécurité / 2FA : s'active à la première action sensible (inviter un membre) : code QR à scanner (Google Authenticator, Authy, 1Password, app Mots de passe) puis code à 6 chiffres ; redemandé ensuite pour ces actions.
Connexion (/auth) : « Mot de passe oublié » → courriel avec lien vers /reset-password ; /register crée un compte ; /verify-email confirme le courriel.
Notifications : la cloche en haut de l'app ; aucune page de réglage des notifications.
Rentabilité d'un job (/jobs/:id) : « Afficher la rentabilité » (main-d'œuvre, dépenses, profit) ; les dépenses se saisissent via Lumi (« ajoute 80 $ de dépenses sur le job 12 »).
PayPal : mode de paiement possible quand on enregistre un paiement sur une facture ; le paiement en ligne des clients passe par Lume Payments (Stripe). Courriels : envoyés par Lume, aucune boîte externe (Gmail, Outlook) à connecter.
Pages reçues par VOS clients (sans compte, sur téléphone) : /quote/:token approuver une soumission, /contract/:token signer, /invoice/:token voir la facture, /pay/:token payer (« Ajouter un pourboire (facultatif) » si les pourboires sont activés ; « Paiement en ligne indisponible » si l'entreprise a désactivé les paiements), /portal/:token portail, /survey/:token noter le service.
Invitation d'équipe (/invite/:token) : page reçue par un membre invité. Portail de migration (/migration/invite/:token) : déposer les fichiers d'export d'un autre CRM. Consentement (/oauth/consent) : autoriser Claude via API & MCP.
Inscription et abonnement (/checkout, /checkout/success) : parcours en 8 étapes (compte, entreprise, équipe, revenus, objectifs, provenance, plan, paiement), « Suivant », « Continuer au paiement », « Activez votre plan » ; « Se connecter » si le compte existe.`;
