-- Backfill NON DESTRUCTIF des traductions EN dans les règles d'automatisation
-- déjà en base. Ajoute body_en/subject_en à chaque action UNIQUEMENT si absent
-- (jamais d'écrasement du texte FR, même personnalisé). Idempotent.
-- Généré depuis automationPresets.data.ts.

create or replace function public._backfill_auto_en(p_key text, p_trads jsonb)
returns void language plpgsql as $fn$
declare r record; new_actions jsonb; i int; act jsonb; tr jsonb;
begin
  for r in select id, actions from public.automation_rules where preset_key = p_key and is_preset = true loop
    new_actions := '[]'::jsonb;
    for i in 0 .. jsonb_array_length(r.actions) - 1 loop
      act := r.actions -> i;
      tr := p_trads -> i;
      if tr is not null then
        -- n'ajoute que si la clé est absente (COALESCE ne remplace pas l'existant)
        if (tr ? 'body_en') and not (act->'config' ? 'body_en') then
          act := jsonb_set(act, '{config,body_en}', tr->'body_en');
        end if;
        if (tr ? 'subject_en') and not (act->'config' ? 'subject_en') then
          act := jsonb_set(act, '{config,subject_en}', tr->'subject_en');
        end if;
      end if;
      new_actions := new_actions || jsonb_build_array(act);
    end loop;
    update public.automation_rules set actions = new_actions, updated_at = now() where id = r.id;
  end loop;
end $fn$;

select public._backfill_auto_en('agreement_signed', '[{"body_en":"Thank you [client_first_name]! Your contract with [company_name] is signed. Your copy: [signed_contract_link]\n[deposit_line]"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Thank you [client_first_name],</h2><p>Your contract with [company_name] is signed. You can view it anytime here:</p><p><a href=\"[signed_contract_link]\">[signed_contract_link]</a></p><p>[deposit_line]</p><p>Talk soon!<br/>[company_name]</p></div>","subject_en":"[company_name] — Contract signed"}]'::jsonb);
select public._backfill_auto_en('appointment_confirmation', '[{"body_en":"Hi [client_first_name], your appointment with [company_name] is confirmed for [appointment_date] at [appointment_time]. See you soon!\n[contract_line]"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Your appointment is confirmed:</p><ul><li><strong>Date:</strong> [appointment_date]</li><li><strong>Time:</strong> [appointment_time]</li><li><strong>Address:</strong> [appointment_address]</li></ul><p>See you soon!<br/>[company_name]</p>[contract_html]</div>","subject_en":"[company_name] — Appointment confirmed"},{}]'::jsonb);
select public._backfill_auto_en('client_anniversary', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>It''s already been a year since we did work at your place — thank you again for your trust!</p><p>If it''s time for a touch-up or some maintenance, just reply to this email and we''ll put together a quote for you.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Already a year!"},{"body_en":"Already a year! Thank you for your trust, [client_first_name]. Need a touch-up? [company_name] is here. Reply STOP to unsubscribe."},{}]'::jsonb);
select public._backfill_auto_en('cross_sell_30d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>It''s been a month since we did work at your place — we hope everything still looks great!</p><p>Did you know we also offer other maintenance services? Reply to this email to learn more.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Checking in with you"},{}]'::jsonb);
select public._backfill_auto_en('deposit_followup_2d', '[{"body_en":"Reminder: your deposit for [company_name] is still pending. Reply to this message if you need any help."},{},{}]'::jsonb);
select public._backfill_auto_en('deposit_received', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Thank you [client_first_name]!</h2><p>Your deposit has been received and your spot on the schedule is reserved.</p><p>We''ll be in touch with the appointment details.</p><p>Talk soon,<br/>[company_name]</p></div>","subject_en":"[company_name] — Deposit received, thank you!"},{"body_en":"Deposit received — thank you [client_first_name]! Your spot is reserved. — [company_name]"},{},{}]'::jsonb);
select public._backfill_auto_en('deposit_reminder', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Thank you for accepting our quote!</p><p>To reserve your spot on the schedule, a deposit is required. Reply to this email if you have any questions about payment.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Deposit required to reserve your spot"},{"body_en":"Thanks for accepting [company_name]''s quote! A deposit is required to reserve your spot on the schedule."},{}]'::jsonb);
select public._backfill_auto_en('estimate_followup', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>We sent you an estimate recently and wanted to follow up.</p><p>Any questions? Just reply to this email — we''d be happy to answer them.</p><p>Best regards,<br/>[company_name]</p></div>","subject_en":"[company_name] — Following up on your estimate"},{}]'::jsonb);
select public._backfill_auto_en('google_review', '[{},{}]'::jsonb);
select public._backfill_auto_en('invoice_sent_reminder_14d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Invoice <strong>[invoice_number]</strong> for <strong>[invoice_total]</strong> has been unpaid for two weeks.</p><p>Please settle it soon. If there''s an issue, reply to this email and we''ll find a solution.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Invoice [invoice_number] unpaid for 2 weeks"},{"body_en":"Hi [client_first_name], reminder: your invoice from [company_name] has been unpaid for 2 weeks. Reply to this message with any questions."},{},{},{}]'::jsonb);
select public._backfill_auto_en('invoice_sent_reminder_1d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Just a friendly reminder: invoice <strong>[invoice_number]</strong> for <strong>[invoice_total]</strong> is awaiting payment.</p><p>If you''ve already paid, please disregard this message.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Reminder: invoice [invoice_number]"},{}]'::jsonb);
select public._backfill_auto_en('invoice_sent_reminder_30d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Invoice <strong>[invoice_number]</strong> for <strong>[invoice_total]</strong> has been overdue for 30 days.</p><p>Please settle it without further delay, or contact us to arrange a payment plan.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Invoice [invoice_number] overdue (30 days)"},{"body_en":"Hi [client_first_name], your invoice from [company_name] has been overdue for 30 days. Please settle it soon or get in touch with us."},{},{},{}]'::jsonb);
select public._backfill_auto_en('invoice_sent_reminder_3d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Invoice <strong>[invoice_number]</strong> for <strong>[invoice_total]</strong> is still awaiting payment.</p><p>If you''ve already paid, please disregard this message.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Reminder: invoice [invoice_number]"},{"body_en":"Hi [client_first_name], just a reminder: your invoice from [company_name] is awaiting payment."},{}]'::jsonb);
select public._backfill_auto_en('invoice_sent_reminder_7d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Invoice <strong>[invoice_number]</strong> for <strong>[invoice_total]</strong> has been pending for a week.</p><p>Please settle it as soon as possible, or reply to this email if something isn''t right.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Invoice [invoice_number] pending for 7 days"},{"body_en":"Hi [client_first_name], your invoice from [company_name] is still pending. Please settle it whenever you can!"},{},{}]'::jsonb);
select public._backfill_auto_en('job_reminder_1d', '[{"body_en":"Reminder: your appointment with [company_name] is tomorrow at [appointment_time]. Reply to this message if you need to reschedule."},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Your appointment is <strong>tomorrow</strong>, [appointment_date] at [appointment_time].</p><p>Something came up? Reply to this email and we''ll find another time.</p><p>See you tomorrow!<br/>[company_name]</p></div>","subject_en":"[company_name] — Your appointment is tomorrow"},{}]'::jsonb);
select public._backfill_auto_en('job_reminder_2h', '[{"body_en":"It''s today! Your appointment with [company_name] is at [appointment_time]. We''re on our way!"},{}]'::jsonb);
select public._backfill_auto_en('job_reminder_7d', '[{"body_en":"Reminder: your appointment with [company_name] is in one week, on [appointment_date] at [appointment_time]."},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Just a reminder: your appointment is scheduled for <strong>[appointment_date]</strong> at <strong>[appointment_time]</strong>.</p><p>Reply to this email if you have any questions or need to reschedule.</p><p>See you soon!<br/>[company_name]</p></div>","subject_en":"[company_name] — Reminder: appointment in one week"},{}]'::jsonb);
select public._backfill_auto_en('lead_followup_14d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>It''s been two weeks since your request — are you still looking for our services?</p><p>Just say the word and we''ll put together a quote for you.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Still interested?"},{},{},{}]'::jsonb);
select public._backfill_auto_en('lead_followup_1d', '[{"body_en":"Hi [client_first_name], do you still need our services? Reply to this message and we''ll take care of you. — [company_name]"},{}]'::jsonb);
select public._backfill_auto_en('lead_followup_3d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>You reached out to us recently and we want to make sure we don''t leave you without an answer.</p><p>Reply to this email and we''ll take care of you right away.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Thinking of you"},{}]'::jsonb);
select public._backfill_auto_en('lost_lead_reengagement', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>It''s been a while! If you have any maintenance or cleaning projects, we''d be happy to help.</p><p>Reply to this email for a no-obligation quote.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Any projects on the go?"},{"body_en":"Hi [client_first_name], it''s been a while! If you have any projects, [company_name] is here. Reply STOP to unsubscribe."},{}]'::jsonb);
select public._backfill_auto_en('no_show_followup', '[{"body_en":"Hi [client_first_name], we missed our appointment. Reply to this message to set up a time that works for you. — [company_name]"},{},{}]'::jsonb);
select public._backfill_auto_en('payment_confirmation', '[{"body_en":"Payment received — thank you [client_first_name]! — [company_name]"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2 style=\"color:#1a1a1a;font-size:18px;\">Thank you [client_first_name]!</h2><p style=\"color:#333;line-height:1.6;\">We confirm receipt of your payment for invoice [invoice_number].</p><p style=\"color:#333;line-height:1.6;\">Thank you for your trust.</p><p style=\"color:#333;line-height:1.6;\">[company_name]</p></div>","subject_en":"Payment received — thank you [client_first_name]!"},{},{}]'::jsonb);
select public._backfill_auto_en('post_appointment_survey', '[{"body_en":"Hi [client_first_name], is everything to your liking since our visit? Reply to this message if anything isn''t right. — [company_name]"},{}]'::jsonb);
select public._backfill_auto_en('quote_followup_14d', '[{"body_en":"Hi [client_first_name], one last follow-up on your quote from [company_name]. We''d love to work with you!"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>We wanted to do one last follow-up about your quote.</p><p>If now isn''t the right time, no problem — just reply and we''ll reconnect whenever it suits you.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Final follow-up on your quote"},{},{},{}]'::jsonb);
select public._backfill_auto_en('quote_followup_1d', '[{"body_en":"Hi [client_first_name], did you get a chance to look over our quote? Reply to this message if you have any questions. — [company_name]"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>We sent you a quote yesterday and wanted to make sure it reached you.</p><p>Any questions? Just reply to this email — we''d be happy to answer them.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Following up on your quote"},{}]'::jsonb);
select public._backfill_auto_en('quote_followup_21d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>We''ll keep your file open a while longer in case you''d like to move ahead with your quote.</p><p>Reply to this email anytime.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — We''re keeping your file open"},{},{}]'::jsonb);
select public._backfill_auto_en('quote_followup_3d', '[{"body_en":"Hi [client_first_name], just a reminder about your quote from [company_name]. We can adjust it if needed!"},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Just a reminder about the quote we sent you.</p><p>If any detail doesn''t work for you, we can adjust it — just let us know.</p><p>Thank you,<br/>[company_name]</p></div>","subject_en":"[company_name] — Your quote is waiting for you"},{}]'::jsonb);
select public._backfill_auto_en('quote_followup_7d', '[{"body_en":"Hi [client_first_name], your quote from [company_name] is still valid. Any questions? Reply to this message."},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>Your quote is still valid and we''re holding your spot.</p><p>If you have any questions or would like to move ahead, reply to this email.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Your quote is still valid"},{},{}]'::jsonb);
select public._backfill_auto_en('reengagement_90d', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>It''s been three months since our last visit — some maintenance might be due.</p><p>Reply to this email and we''ll find you a spot on the schedule.</p><p>Looking forward,<br/>[company_name]</p></div>","subject_en":"[company_name] — Already 3 months!"},{"body_en":"Hi [client_first_name], already 3 months! Some maintenance might be due. — [company_name] Reply STOP to unsubscribe."},{}]'::jsonb);
select public._backfill_auto_en('review_reminder_7d', '[{"body_en":"Hi [client_first_name], a Google review would help us out a lot: [google_review_url] Thanks again! — [company_name]"},{}]'::jsonb);
select public._backfill_auto_en('seasonal_reminder_6m', '[{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2>Hi [client_first_name],</h2><p>The season is coming up — now''s a good time to get your property ready.</p><p>Reply to this email for a quick, no-obligation quote.</p><p>Talk soon,<br/>[company_name]</p></div>","subject_en":"[company_name] — The season is coming"},{"body_en":"The season is coming up! [company_name] can get your property ready. Reply to this message for a quote. Reply STOP to unsubscribe."},{}]'::jsonb);
select public._backfill_auto_en('stale_lead_7d', '[{"body_en":"Hi [client_first_name], we haven''t forgotten you! Still interested in our services? — [company_name]"},{},{}]'::jsonb);
select public._backfill_auto_en('thank_you_after_job', '[{"body_en":"Thank you for doing business with [company_name], [client_first_name]! If anything isn''t perfect, reply to this message."},{}]'::jsonb);
select public._backfill_auto_en('welcome_new_lead', '[{"body_en":"Hi [client_first_name], thank you for contacting [company_name]! We''ll get back to you very soon."},{"body_en":"<div style=\"font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;\"><h2 style=\"color:#1a1a1a;font-size:18px;\">Hi [client_first_name],</h2><p style=\"color:#333;line-height:1.6;\">Thank you for reaching out to us. We''ve received your request and will get back to you very quickly.</p><p style=\"color:#333;line-height:1.6;\">If your request is urgent, reply to this email — we''ll handle it as a priority.</p><p style=\"color:#333;line-height:1.6;\">[company_name]</p></div>","subject_en":"Thank you for contacting [company_name]"},{},{}]'::jsonb);

drop function public._backfill_auto_en(text, jsonb);
